### PR TITLE
Develop a clone of Newsweek Website

### PR DESCRIPTION
**Pull request by kagaramag**
## Title
Design a mirror of Newsweek website

This is a basic HTML page, a clone of Newsweek website, only with educational purposes. You can download this project and run using your browser.

## Live demo
[Demo](https://raw.githack.com/kagaramag/nw-clone/develop/index.html)

## Screenshot
image

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @kagaramag :clap: 
You have done an awesome job putting this together and getting this far! You have some changes to make and as such, please consider my comments below

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out. Please take not of the navigation, bar content running into other content, etc.
screenshot
screenshot
screenshot


##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @kagaramag 
### You have done a really good job so far :clap: and also for implementing changes from the previous review. However, there are a few changes you need to make before your project could be approved. 
- Remove horizontal scroll from medium and mobile devices
- Also, the space between the image and text is quite big on medium and small devices, solve this and any other place 
spacing
### Make these changes and resubmit for another code review. Good luck.
- For assistance, contact me on slack @iamraymond
- Happy coding!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @kagaramag      
#### Great Job so far, but there is just one more to be worked on. 
### General
- [x] Kindly enable stickler for this project.

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by lekegitrepo** [comment]
### This PR is under Review by: [TSE] _Temitayo Adeleke_

**Comment by lekegitrepo** [comment]
### Hi @kagaramag 👏  👏
**_Good job. The required change has been implemented. So, this project is approved_**

### Reviewed by: _Temitayo Adeleke_

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved

**Pull request merged**
